app = "arxiv-paper-hunter"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "./run_tracker.sh"

[experimental]
  auto_start_machines = true
  auto_stop_machines = true
